apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    purpose: gitops-owncloud
  name: gitops-owncloud-vol
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitops-owncloud-pvc
    namespace: gitops
  nfs:
    path: /var/vols/itom/gitops/owncloud
    server: fs-464c74f2.efs.us-east-1.amazonaws.com
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gitops-owncloud
  volumeMode: Filesystem
