apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    purpose: gitops-owncloud
  name: gitops-owncloud-pvc
  namespace: gitops
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: gitops-owncloud
  storageClassName: gitops-owncloud
  volumeMode: Filesystem
  volumeName: gitops-owncloud-vol
